#!/command/with-contenv bash

if [ $NAIVE_SERVER_ADDRESS_3 ];then
    echo "starting naiveproxy: /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_3} --proxy=${NAIVE_SERVER_ADDRESS_3} ${NAIVE_EXTRA_3}"
    s6-setuidgid abc /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_3} --proxy=${NAIVE_SERVER_ADDRESS_3} ${NAIVE_EXTRA_3}
else
    echo "naiveproxy-3 is not enabled"
fi

while true; do sleep 60; done