#!/command/with-contenv bash

if [ $NAIVE_SERVER_ADDRESS_8 ];then
    echo "starting naiveproxy: /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_8} --proxy=${NAIVE_SERVER_ADDRESS_8} ${NAIVE_EXTRA_8}"
    s6-setuidgid abc /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_8} --proxy=${NAIVE_SERVER_ADDRESS_8} ${NAIVE_EXTRA_8}
else
    echo "naiveproxy-8 is not enabled"
fi

while true; do sleep 60; done