#!/command/with-contenv bash

if [ $NAIVE_SERVER_ADDRESS_1 ];then
    echo "starting naiveproxy: /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_1} --proxy=${NAIVE_SERVER_ADDRESS_1} ${NAIVE_EXTRA_1}"
    s6-setuidgid abc /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_1} --proxy=${NAIVE_SERVER_ADDRESS_1} ${NAIVE_EXTRA_1}
else
    echo "naiveproxy-1 is not enabled"
fi

while true; do sleep 60; done