#!/command/with-contenv bash

if [ $NAIVE_SERVER_ADDRESS_6 ];then
    echo "starting naiveproxy: /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_6} --proxy=${NAIVE_SERVER_ADDRESS_6} ${NAIVE_EXTRA_6}"
    s6-setuidgid abc /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_6} --proxy=${NAIVE_SERVER_ADDRESS_6} ${NAIVE_EXTRA_6}
else
    echo "naiveproxy-6 is not enabled"
fi

while true; do sleep 60; done