#!/command/with-contenv bash

if [ $NAIVE_SERVER_ADDRESS_9 ];then
    echo "starting naiveproxy: /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_9} --proxy=${NAIVE_SERVER_ADDRESS_9} ${NAIVE_EXTRA_9}"
    s6-setuidgid abc /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_9} --proxy=${NAIVE_SERVER_ADDRESS_9} ${NAIVE_EXTRA_9}
else
    echo "naiveproxy-9 is not enabled"
fi

while true; do sleep 60; done