#!/command/with-contenv bash

if [ $NAIVE_SERVER_ADDRESS_4 ];then
    echo "starting naiveproxy: /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_4} --proxy=${NAIVE_SERVER_ADDRESS_4} ${NAIVE_EXTRA_4}"
    s6-setuidgid abc /usr/bin/naive --listen=${NAIVE_LISTEN_ADDRESS_4} --proxy=${NAIVE_SERVER_ADDRESS_4} ${NAIVE_EXTRA_4}
else
    echo "naiveproxy-4 is not enabled"
fi

while true; do sleep 60; done